### ISSUE TITLE
MJCF: Unable to set the `name` attribute for `<body>` despite being configured to accept it in the schema

### ISSUE THREAD

**Issue by kylevedder** [deepmind/dm_control#174]
When trying to set the `name` attribute of a `<body>` using the following example:

```
model = mjcf.RootElement()
# Create a simple geom
model.worldbody.add('geom', name='mygeom', type='ellipsoid', size=(1, 1, 0.1), rgba=[1, 0, 0, 1])
# Create a simple spawn
arena = mjcf.RootElement()
spawn_site = arena.worldbody.add('site', name="myspawn", pos=(0, 0, 0), group=3, euler=np.array([0, 0, 0.1]))
body = spawn_site.attach(model)
body.set_attributes(name="mybody")
body.add('freejoint', name=f"myjoint")
print(arena.to_xml_string())
```

I get the following error:

```
Traceback (most recent call last):
  File "./random_scene.py", line 72, in <module>
    body.set_attributes(name="mybody")
  File "/home/k/miniconda3/envs/dmcontrol/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 534, in set_attributes
    old_value = self._get_attribute(attribute_name)
  File "/home/k/miniconda3/envs/dmcontrol/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 507, in _get_attribute
    self._check_valid_attribute(attribute_name)
  File "/home/k/miniconda3/envs/dmcontrol/lib/python3.7/site-packages/dm_control/mjcf/element.py", line 504, in _check_valid_attribute
    attribute_name, self._spec.name))
AttributeError: 'name' is not a valid attribute for <body>
```

Note however that if I comment out `body.set_attributes(name="mybody")`, it prints the following XML:

```
<mujoco model="unnamed_model">
  <default>
    <default class="/"/>
    <default class="unnamed_model/"/>
  </default>
  <worldbody>
    <site name="myspawn" class="/" group="3" pos="0 0 0" euler="0 0 0.10000000000000001"/>
    <body pos="0 0 0" euler="0 0 0.10000000000000001" name="unnamed_model/">
      <freejoint name="unnamed_model/myjoint/"/>
      <geom name="unnamed_model/mygeom" class="unnamed_model/" type="ellipsoid" size="1 1 0.10000000000000001" rgba="1 0 0 1"/>
    </body>
  </worldbody>
</mujoco>
```

but as you can see, the created `<body>` has a `name` attribute set to a default value (`"unnamed_model/"`), so there's no reason I shouldn't be able to set a custom one.

The `AttributeError` is generated because `name` is not within the known set of attributes for `<body>`, [as per the assert in `mjcf/element.py`](https://github.com/deepmind/dm_control/blob/a669634a9bdd5be5d78654b2370f9ef8fd987817/dm_control/mjcf/element.py#L501). Upon inspection, the accepted attributes are `'mocap', 'pos', 'quat', 'axisangle', 'xyaxes', 'zaxis', 'euler'`, which I got via`print(body._spec.attributes.keys())` run at the end of the above example. It seems like the attributes accepted is configured via the [`mjcf/schema.xml`](https://github.com/deepmind/dm_control/blob/master/dm_control/mjcf/schema.xml) file, and messing around locally I was able to confirm that I was able to delete accepted attributes for `<body>` by deleting them from this `schema.xml` file. However, the `schema.xml` for `<body>` seems to already be configured to [accept a `name` attribute](https://github.com/deepmind/dm_control/blob/a669634a9bdd5be5d78654b2370f9ef8fd987817/dm_control/mjcf/schema.xml#L1015), but for some reason this is not being reflected in the component generated. 

At this point, my best guess is that either there is a problem with the `schema.xml` (I looked at it closely to see if there were any typos, to no avail), there is a bug in the parser/element creator, or there is some other gotcha that I am unaware of. Any insight on any of these fronts would be appreciated.

**Comment by kylevedder** [comment]
It seems [this is a known gotcha](https://github.com/deepmind/dm_control/tree/master/dm_control/mjcf#attachment-frames), closing.
