### ISSUE TITLE
Rendering error (gladLoadGL error) by using osmesa backend

### ISSUE THREAD

**Issue by dongleecsu** [deepmind/dm_control#365]
Hi,

I am using Python3.7 on a headless Ubuntu 18.04 server with CUDA 10.2. Here are my mujoco related versions: `dm-control=1.0.8 ` and `mujoco=2.3.0`. When using dm-control.suite, it report the following error. BTW, I set the rendering backend to `osmesa` by adding this line to my code `os.environ['MUJOCO_GL'] = 'osmesa'`. Can you please help me to tackle it? Thanks in advance.

```text
render_context: <dm_control._render.pyopengl.osmesa_renderer.OSMesaContext object at 0x7f950019d910>
Traceback (most recent call last):
  File "wrappers.py", line 430, in <module>
    obs = env.reset()
  File "wrappers.py", line 294, in reset
    obs = self._env.reset()
  File "wrappers.py", line 115, in reset
    obs = self._env.reset()
  File "wrappers.py", line 160, in reset
    return self._env.reset()
  File "wrappers.py", line 76, in reset
    obs['image'] = self.render()
  File "wrappers.py", line 82, in render
    return self._env.physics.render(*self._size, camera_id=self._camera)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 221, in render
    scene_callback=scene_callback)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 696, in __init__
    if self._physics.contexts.mujoco is not None:
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 527, in contexts
    self._make_rendering_contexts()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/mujoco/engine.py", line 513, in _make_rendering_contexts
    mujoco_context = wrapper.MjrContext(self.model, render_context)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/mujoco/wrapper/core.py", line 606, in __init__
    ptr = ctx.call(mujoco.MjrContext, model.ptr, font_scale)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/_render/executor/render_executor.py", line 196, in call
    return self._call_locked(func, *args, **kwargs)
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/site-packages/dm_control/_render/executor/render_executor.py", line 206, in _call_locked
    return self._executor.submit(func, *args, **kwargs).result()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ma-user/anaconda3/envs/PyTorch-1.8/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
mujoco.FatalError: gladLoadGL error
```

**Comment by dongleecsu** [comment]
Finally, I work it out. I change the rendering backend to `egl` by using `os.environ['MUJOCO_GL'] = 'egl'`. Then, an important step needed: `sudo apt-get install libnvidia-gl-440-server` as mentioned in [issue 214](https://github.com/deepmind/dm_control/issues/214).
