### ISSUE TITLE
Load task failed

### ISSUE THREAD

**Issue by Capri2014** [deepmind/dm_control#5]
Thanks for sharing this great work to us!

I was able to successfully import suite by running `from dm_control import suite` but  when I run 

`env = suite.load(domain_name="pendulum", task_name="swingup")`

I got

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/suite/__init__.py", line 110, in load
    visualize_reward)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/suite/__init__.py", line 140, in build_environment
    env = domain.SUITE[task_name](**task_kwargs)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/suite/pendulum.py", line 50, in swingup
    physics = Physics.from_xml_string(*get_model_and_assets())
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/mujoco/engine.py", line 344, in from_xml_string
    return cls.from_model(model)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/mujoco/engine.py", line 327, in from_model
    return cls(data)
  File "/home/luoqi06/.local/lib/python2.7/site-packages/dm_control/mujoco/engine.py", line 120, in __init__
    self._reload_from_data(data)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/mujoco/engine.py", line 306, in _reload_from_data
    render_context = render.Renderer(_MAX_WIDTH, _MAX_HEIGHT)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/render/base.py", line 44, in __init__
    self._create(max_width, max_height)
  File "/home/xxxx/.local/lib/python2.7/site-packages/dm_control/render/glfw_renderer.py", line 44, in _create
    glfw.window_hint(glfw.DOUBLEBUFFER, 0)
  File "/home/xxxx/.local/lib/python2.7/site-packages/glfw.py", line 978, in window_hint
    _glfw.glfwWindowHint(target, hint)
  File "/home/xxxx/.local/lib/python2.7/site-packages/glfw.py", line 617, in errcheck
    _reraise(exc[1], exc[2])
  File "/home/xxxx/.local/lib/python2.7/site-packages/glfw.py", line 39, in _reraise
    raise (exception, None, traceback)
glfw.GLFWError: (65539) Invalid argument for enum parameter

```

**Comment by yotam** [comment]
It sounds like you may have an older version of GLFW. Can you tell us a bit more about your system? We can try to reproduce.

**Comment by alimuldal** [comment]
Closing due to inactivity
