### ISSUE TITLE
Can't launch the viewer

### ISSUE THREAD

**Issue by tkelestemur** [deepmind/dm_control#55]
I am getting the following for the `viewer.launch(env)` function. 

```
Traceback (most recent call last):
  File "/home/tarik/dm_test.py", line 8, in <module>
    viewer.launch(env)
  File "/home/tarik/develop/py-envs/rl/local/lib/python2.7/site-packages/dm_control/viewer/__init__.py", line 42, in launch
    app = application.Application(title=title, width=width, height=height)
  File "/home/tarik/develop/py-envs/rl/local/lib/python2.7/site-packages/dm_control/viewer/application.py", line 191, in __init__
    self._window = gui.RenderWindow(width, height, title)
  File "/home/tarik/develop/py-envs/rl/local/lib/python2.7/site-packages/dm_control/viewer/gui/__init__.py", line 35, in ErrorRenderWindow
    'Cannot create a window because no windowing system could be imported')
ImportError: Cannot create a window because no windowing system could be imported
Exception RuntimeError: RuntimeError('This executor has already been terminated.',) in <function callback at 0x7f106b5350c8> ignored
```

I belive osmesa is currently being used:
```
In [2]: render.BACKEND
Out[2]: 'osmesa'
```

My setup is Ubuntu 16.04, Python 2.7 with virtualenv. 

PS. MuJoCo by itsel works fine.

**Comment by alimuldal** [comment]
Although we support both GLFW and OSMesa (on Linux) for offscreen rendering, the viewer requires GLFW. By default the `render` module will first try to import the GLFW backend, and if that fails then it will fall back on OSMesa, which might be what's happening in your case. You can try forcing GLFW by setting the environment variable `MUJOCO_GL=glfw` before launching your interpreter, then if the GLFW backend can't be imported for whatever reason then you'll get an error instead of silently falling back on OSMesa.

Possible explanations for why GLFW might not be importable:
* Is X11 available (e.g. are you trying to launch the viewer over SSH)? GLFW requires X11.
* Are you missing any of the dependencies mentioned [here][1]?

[1]: https://github.com/deepmind/dm_control#additional-instructions-for-linux
