### ISSUE TITLE
RenderWindow is None / Can't load EGL

### ISSUE THREAD

**Issue by iandanforth** [deepmind/dm_control#78]
System: Windows 10

While trying to run `explore.py` I encountered this error. It appears that an ImportError is being silently swallowed in dm_control.viewer.gui.\_\_init\_\_.py. The underlying error is that EGL cannot be loaded.

Is there some additional install / config step required to get EGL working? 

Traceback (most recent call last):
  File "dm_control\suite\explore.py", line 84, in <module>
    app.run(main)
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "dm_control\suite\explore.py", line 80, in main
    viewer.launch(loader)
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\__init__.py", line 42, in launch
    app = application.Application(title=title, width=width, height=height)
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\application.py", line 191, in __init__
    self._window = gui.RenderWindow(width, height, title)
TypeError: 'NoneType' object is not callable

---------------------------------

The swallowed error is

Traceback (most recent call last):
  File "dm_control\suite\explore.py", line 27, in <module>
    from dm_control import viewer
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\__init__.py", line 22, in <module>
    from dm_control.viewer import application
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\application.py", line 24, in <module>
    from dm_control.viewer import gui
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\gui\__init__.py", line 25, in <module>
    from dm_control.viewer.gui import glfw_gui
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\gui\glfw_gui.py", line 25, in <module>
    from dm_control.viewer.gui import base
  File "C:\Users\Ian\AppData\Roaming\Python\Python36\site-packages\dm_control\viewer\gui\base.py", line 28, in <module>
    from OpenGL import GL
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\site-packages\OpenGL\platform\egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, 'The specified module could not be found', None, 126, None, 'EGL', None)

**Comment by iandanforth** [comment]
Solved. Hadn't set the MUJOCO_GL env var and it was grumpy about this.

If I might suggest this might be improved by:

1. Moving the env var instructions out of the Linux section on the main Readme
2. Adding a helpful error in gui\__init__.py rather than `pass`

or with more effort

3. If the env var isn't set, auto-detect if any of the backends will work and use the first that does.

I'm happy to do 1 and/or 2 if you're ok with me opening a PR.
