### ISSUE TITLE
RuntimeError: This executor has already been terminated.

### ISSUE THREAD

**Issue by ruifengma** [deepmind/dm_control#79]
I got the error each time after the program has been terminated, the overall program is runnable, but just when it has been finished, this error raised.
`Exception ignored in: <function _create_finalizer.<locals>.callback at 0x10d7eb510>
Traceback (most recent call last):
  File "/Users/ruifengma/.virtualenvs/dm/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 266, in callback
  File "/Users/ruifengma/.virtualenvs/dm/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 749, in finalize_mjr_context
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
  File "/Users/ruifengma/.virtualenvs/dm/lib/python3.6/site-packages/dm_control/_render/base.py", line 109, in make_current
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
  File "/Users/ruifengma/.virtualenvs/dm/lib/python3.6/site-packages/dm_control/_render/executor/render_executor.py", line 95, in execution_context
  File "/Users/ruifengma/.virtualenvs/dm/lib/python3.6/site-packages/dm_control/_render/executor/render_executor.py", line 90, in _check_not_terminated
RuntimeError: This executor has already been terminated.`

**Comment by alimuldal** [comment]
Yes, that's expected - see https://github.com/deepmind/dm_control/issues/61#issuecomment-437968667. Those errors are a bit annoying, but otherwise benign.
